# This is a placeholder workflow in the master branch
# for a manually triggered wrims compute in the wrims-comparison-test branch

name: WRIMS verification compute
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      - name: Run a one-line script
        run: echo Hello, master branch!